# Generated by Django 3.0.7 on 2020-08-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=120, unique=True, verbose_name='Job #')),
                ('job_name', models.CharField(max_length=120, verbose_name='Job Name')),
            ],
            options={
                'permissions': (('view_this_job', 'View Job'),),
            },
        ),
    ]
