# Generated by Django 3.0.7 on 2020-08-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('view_this_job', 'View Job In Website'),)},
        ),
    ]
