# Generated by Django 3.0.7 on 2020-08-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200806_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Job Name'),
        ),
    ]
