"""
Django settings for geo project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from .settings_shared import *

SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    from .secrets import SECRET_KEY # should throw an error in production if secretkey is not present

POSTGIS_PASSWORD = os.environ.get("POSTGIS_PASSWORD")
if not POSTGIS_PASSWORD:
    from .secrets import POSTGIS_PASSWORD

POSTGIS_HOST = os.environ.get("POSTGIS_HOST") or "172.17.0.2"
POSTGIS_PORT = os.environ.get("POSTGIS_PORT") or ""
POSTGIS_USER = os.environ.get("POSTGIS_USER") or "geodjango"
POSTGIS_NAME = os.environ.get("POSTGIS_NAME") or "geodjango"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["geo.trevor-sullivan.tech", "geoprod.trevor-sullivan.tech", "localhost"]

ADMINS = [("Trevor", 'trevor@trevor-sullivan.tech')] # TODO setup email so this works

SERVER_EMAIL = 'django@trevor-sullivan.tech'

# Application definition


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': POSTGIS_NAME,
        'USER': POSTGIS_USER,
        'PASSWORD': POSTGIS_PASSWORD,
        "HOST": POSTGIS_HOST,
        "PORT": POSTGIS_PORT,
    }
}

