# Generated by Django 3.0.5 on 2020-07-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_no', models.CharField(max_length=120)),
                ('job_no', models.CharField(max_length=120)),
                ('job_name', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('silty_clay', 'Silty Clay'), ('silt', 'Silt'), ('clean_sand', 'Clean Sand')], max_length=32)),
                ('texture', models.CharField(choices=[('fine', 'Fine'), ('fine_coarse', 'Fine-coarse'), ('granular_fine', 'Granular Fine'), ('med_fine', 'Med Fine'), ('med_fine_coarse', 'Med Fine-coarse'), ('coarse', 'Coarse'), ('very_fine', 'Very Fine')], max_length=32)),
                ('color', models.CharField(choices=[('dark_brwn', 'Dark Brown'), ('med_brwn', 'Med Brown'), ('redish_brwn', 'Redish Brown'), ('brown_beige', 'Brown Beige'), ('light_brown', 'Light Brown'), ('tan', 'Tan'), ('dark_light_brown', 'Dark brown/light brown'), ('med_brown_tan', 'Med Brown/Tan'), ('brown_grey', 'Brown/grey'), ('brown', 'Brown'), ('beige', 'Beige'), ('pink', 'pink')], max_length=32)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redox_potential', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conductivity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('chloride', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sulfate', models.DecimalField(decimal_places=1, max_digits=10)),
                ('salinity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resistivity_as_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resistivity_saturated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbonate', models.BooleanField()),
                ('sulfide', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('trace', 'Trace')], max_length=32)),
                ('moisture_content', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField()),
            ],
        ),
    ]
