# Generated by Django 3.0.5 on 2020-07-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='moisture_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
