# Generated by Django 3.0.5 on 2020-07-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20200703_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='awwa',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
