# Generated by Django 3.0.5 on 2020-07-20 19:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20200705_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
