# Generated by Django 3.0.7 on 2020-07-28 22:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_auto_20200722_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='carbonate',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sample',
            name='color',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='sample',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='resistivity_as_collected',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='soil_type',
            field=models.CharField(choices=[('clay_blue_gray', 'Clay (blue-gray)'), ('clay_stone', 'Clay/Stone'), ('clay', 'Clay'), ('silt', 'Silt'), ('clean_sand', 'Clean Sand')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sulfide',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sample',
            name='texture',
            field=models.CharField(max_length=32),
        ),
    ]
