# Generated by Django 3.0.7 on 2020-07-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_auto_20200728_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='wssc',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='depth',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Depth (feet)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ph',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='soil_type',
            field=models.CharField(choices=[('clay_blue_gray', 'Clay (blue-gray)'), ('clay_stone', 'Clay/Stone'), ('clay', 'Clay'), ('silt', 'Silt'), ('sand', 'Sand')], max_length=32),
        ),
    ]
