# Generated by Django 3.0.7 on 2020-08-05 18:59

from decimal import Decimal
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_auto_20200731_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='awwa',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='AWWA Rating'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='carbonate',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=32, verbose_name='Carbonate'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='chloride',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Chloride (ppm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='color',
            field=models.CharField(max_length=32, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='conductivity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Conductivity (µS/cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='job_name',
            field=models.CharField(max_length=120, verbose_name='Job Name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='job_no',
            field=models.CharField(max_length=120, verbose_name='Job #'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='moisture_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Moisture Content (%)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ph',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\xa0pH'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='sample',
            name='redox_potential',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Redox Potential (mV)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='resistivity_as_collected',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Resistivity As Collected (KΩ-cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='resistivity_saturated',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Resistivity Saturated (KΩ-cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='salinity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salinity (%)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_no',
            field=models.CharField(max_length=120, unique=True, verbose_name='Sample #'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='soil_type',
            field=models.CharField(choices=[('clay_blue_gray', 'Clay (blue-gray)'), ('clay_stone', 'Clay/Stone'), ('clay', 'Clay'), ('silt', 'Silt'), ('sand', 'Sand')], max_length=32, verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sulfate',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Sulfate (ppm'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sulfide',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=32, verbose_name='Sulfide'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='texture',
            field=models.CharField(max_length=32, verbose_name='Texture'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='wssc',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='WSSC Rating'),
        ),
    ]
