# Generated by Django 3.0.7 on 2020-09-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_auto_20200903_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='field_resistivity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Field Resistivity(Ω-cm)'),
        ),
    ]
